### ISSUE TITLE
Twoslash error occurs when building nuxt.

### ISSUE THREAD

**Issue by ikxin** [nuxt/nuxt.com#1705]
I found many Twoslash errors while building the nuxt documentation. Is this expected?

```
#12 755.8  ERROR 
#12 755.8 ## Errors were thrown in the sample, but not included in an error tag
#12 755.8 
#12 755.8 These errors were not marked as being expected: 2322. 
#12 755.8 Expected: // @errors: 2322
#12 755.8 
#12 755.8 Compiler Errors:
#12 755.8 
#12 755.8 index.tsx
#12 755.8   [2322] 240 - Type 'string' is not assignable to type 'NavigationGuard'.
#12 755.8 
#12 755.8   ## Errors were thrown in the sample, but not included in an error tag
#12 755.8   
#12 755.8   These errors were not marked as being expected: 2322.
#12 755.8   Expected: // @errors: 2322
#12 755.8   
#12 755.8   Compiler Errors:
#12 755.8   
#12 755.8   index.tsx
#12 755.8   [2322] 240 - Type 'string' is not assignable to type 'NavigationGuard'.
#12 755.8   at validateCodeForErrors (node_modules/.pnpm/twoslash@0.2.12_typescript@5.6.3/node_modules/twoslash/dist/core.mjs:41:20)
#12 755.8   at twoslasher2 (node_modules/.pnpm/twoslash@0.2.12_typescript@5.6.3/node_modules/twoslash/dist/core.mjs:346:7)
#12 755.8   at twoslasher (node_modules/.pnpm/twoslash-vue@0.2.12_typescript@5.6.3/node_modules/twoslash-vue/dist/index.mjs:89:20)
#12 755.8   at Object.preprocess (node_modules/.pnpm/@shikijs+twoslash@1.22.2_typescript@5.6.3/node_modules/@shikijs/twoslash/dist/core.mjs:1127:30)
#12 755.8   at Object.preprocess (node_modules/.pnpm/@shikijs+vitepress-twoslash@1.22.2_@nuxt+kit@3.13.2_magicast@0.3.5_rollup@4.24.3_webpack-sources@3.2.3__typescript@5.6.3/node_modules/@shikijs/vitepress-twoslash/dist/index.mjs:213:34)
#12 755.8   at codeToHast (node_modules/.pnpm/@shikijs+core@1.22.2/node_modules/@shikijs/core/dist/index.mjs:1158:37)
#12 755.8   at Object.codeToHast (node_modules/.pnpm/@shikijs+core@1.22.2/node_modules/@shikijs/core/dist/index.mjs:1825:37)
#12 755.8   at highlighter (node_modules/.cache/nuxt/.nuxt/prerender/chunks/build/mdc-highlighter.mjs:98:25)
#12 755.8   at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
#12 755.8   at async Object.handler (node_modules/.cache/nuxt/.nuxt/prerender/chunks/nitro/nitro.mjs:4141:10)
#12 755.8
```

Example:

![Image](https://github.com/user-attachments/assets/fbd30e58-e5e8-4567-b9c6-28b5d69d84c4)

**Comment by danielroe** [comment]
cc: @antfu

**Comment by antfu** [comment]
You could ignore them for now as they don't block the build. But indeed we need to update your docs to improve those types.

**Comment by ikxin** [comment]
@antfu Its syntax seems correct, but the result built is incorrect. Is there any good way to solve this?

https://nuxt.com/docs/getting-started/testing#%EF%B8%8F-helpers

![Image](https://github.com/user-attachments/assets/6379b4ff-04d6-4638-855a-108d9ed034a3)

**Comment by oneminch** [comment]
@ikxin This issue can be closed since corresponding PR is merged.

**Comment by ikxin** [comment]
@oneminch Thank you for your reminder. It is closed.
